---
title: 'Tidy Tuesday: Australian Pets (2020-07-21)'
author: "Christopher Beltz"
date: "7/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load packages

```{r}
#load packages
library(here)
library(tidyverse) 
library(tidytuesdayR)
library(viridis)
library(rphylopic)
```


Read in data

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-07-21')

animal_outcomes <- tuesdata$animal_outcomes
animal_complaints <- tuesdata$animal_complaints
brisbane_complaints <- tuesdata$brisbane_complaints
```


Transform data

```{r}
#code adapted from @pedrodrocha via https://github.com/pedrodrocha/TidyTuesday/tree/master/21-07-2020_Australian_Pets
animal_outcomes_LONG <- animal_outcomes %>%
  pivot_longer(
    ACT:Total,
    names_to = "state",
    values_to = "number"
  ) %>%  
  mutate( 
    state = case_when(
      state == "ACT"   ~ "Australian Capital Territory",
      state == "NSW"   ~ "New South Wales",
      state == "NT"    ~ "Northern Territory",
      state == "QLD"   ~ "Queensland",
      state == "SA"    ~ "South Australia",
      state == "TAS"   ~ "Tasmania",
      state == "VIC"   ~ "Victoria",
      state == "WA"    ~ "Western Australia",
      state == "Total" ~ "Australia"
      )
    )
```


```{r}
animal_outcomes_LONG <- animal_outcomes_LONG %>% 
  filter(state == "Australia") %>% 
  filter(!outcome %in% c("Other", "Currently In Care")) %>% 
  filter(animal_type %in% c("Dogs", "Cats"))
```



Create function for inserting images in ggplot facets

```{r}
#custom function create by @baptiste
#Original post: https://stackoverflow.com/questions/32807665/removing-one-tablegrob-when-applied-to-a-box-plot-with-a-facet-wrap?answertab=votes#tab-top
#Additional post: https://stackoverflow.com/questions/44688623/adding-custom-images-to-ggplot-facets

require(ggplot2)
require(grid)
require(png)
require(RCurl)

annotation_custom2 <- 
function (grob, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, data){ layer(data = data, stat = StatIdentity, position = PositionIdentity, 
        geom = ggplot2:::GeomCustomAnn,
        inherit.aes = TRUE, params = list(grob = grob, 
                                          xmin = xmin, xmax = xmax, 
                                          ymin = ymin, ymax = ymax))}
```


```{r}
#obtain cat and dog image using `rphylopic` package
dog <- name_search(text = "dog", options = "namebankID")[[1]]
name_get(uuid = dog$uid[1], options = c('citationStart', 'html'))
name_images(uuid = dog$uid[1])
img_dog <- image_data("3c534a59-fd0c-41bb-80c7-1d18db9bae13", size = "512")[[1]]

cat <- name_search(text = "Felis catus", options = "namebankID")[[1]]
name_get(uuid = cat$uid[1], options = c('citationStart', 'html'))
name_images(uuid = cat$uid[1])
img_cat <- image_data("cc22d71c-a014-41a9-aaf1-5f2cffad6121", size = "512")[[1]]

#create annotation using custom function
anno_cat <- annotation_custom2(rasterGrob(img_cat, interpolate=TRUE), xmin=2014, xmax=2018, ymin=34000, ymax=44000, data=animal_outcomes_LONG[4,]) #set brackets to row with cat data
anno_dog <- annotation_custom2(rasterGrob(img_dog, interpolate=TRUE), xmin=2014, xmax=2018, ymin=34000, ymax=44000, data=animal_outcomes_LONG[1,]) #set brackets to row with dog data
```



Plot It!

```{r}
p0 <- ggplot(data = animal_outcomes_LONG,
       mapping = aes(x = year, y = number, color = outcome))
       
p1 <- p0 + geom_line(size=0.9) +
  facet_wrap(~animal_type)

p2 <- p1 + 
  ylab("Total Number") +
  xlab("Year")

p3 <- p2 + scale_fill_viridis() + 
  theme_bw() +
  theme(panel.grid.major = element_blank(),
       panel.grid.minor = element_blank()) +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  theme(legend.title = element_blank(), legend.position = "top") 

p4 <- p3 + anno_cat + anno_dog

p4
```


```{r, eval=FALSE}
ggsave(filename="Tidy-Tuesday_2020-07-21.jpg",
       path=here("2020-07-21_Australian-Pets", "plot"),
       bg="transparent", 
       units="in",
       width=9.5,
       height=6)
```
